import LocalizedStrings from 'react-localization';

let localization = new LocalizedStrings({
 en:{
   home_freshtrack:"FreshTrak is here to help!",
   home_stay:"Stay Up to Date",
   home_findfood:"Find Food",
   home_comming_soon:"Coming soon... Make a FreshTrak account to stay up to date on local food access events.",
   home_zip_details: "Enter your zip code and get connected to food access resources in your community.",
   home_header_component:"We’re here to help! Input your zip code to find food access resources in your community.",
   home_dashboard: "Serve More Families",
   home_dashboard_org: "Prepare your organization for the influx of demand for food by streamlining registration, planning service windows, and forecasting needs. Serve more families—both current and new—in your community.",
   home_before_footer1: "Register neighbors ahead of time or,where possible, schedule a pick-up appointment, your organization can plan for any increase in demand.",
   home_before_footer2: "You post food access “events” in your community—anything from daily pantry hours to pop-up food events—and neighbors enter their zip code to get connected to them.",
   home_before_footer3: "Remove the bottleneck from distribution with online customer pre-registration. Serve more customers, faster!",
   home_before_footer1_header: "Predict Need",
   home_before_footer2_header: "Serve Food",
   home_before_footer3_header:"Move Quickly",
   search_for_resources: "Search For Resources",
   resource_zip_code: "Resource Events In Zip Code",
   resource_zip_code_events:"Resource Events Serving Residents of Zip Code",
   no_events_scheduled:"No Events Currently Scheduled",
   refine_your_results:"REFINE YOUR RESULTS",
   by_distance: "by Distance",
   by_service_catogory: "by Service Category",
   register: "Register Now.",
   save_time: "Save Time.",
   stay_safe: "Private and Secure.",
   register_who_are_you:"What is your name?",
   first_name: "First Name",
   middle_name: "Middle Name",
   last_name: "Last Name",
   suffix: "Suffix",
   dob:"Date of Birth",
   gender: "Gender",
   register_where_you_live: "Where do you live?",
   street_address: "Street Address",
   lot_suite: "apt/lot/suite",
   city:"City",
   state:"State",
   zip_code:"Zip Code",
   register_how_to_contact: "How to Contact You",
   phone_number: "Phone Number (Mobile Preferred)",
   no_phone: "No Phone Available",
   phone_contact_you: "Is it okay to contact you with updates and information about your registration, and updates to our network?",
   no_email: "No Email Available",
   email_contact_you:"Is it okay to email you with updates and information about your registration, and updates to our network?",
   register_about_family:"Tell us about your family",
   family_count: "How many additional family members are in each age group? (Do not include yourself)",
   seniors:"Seniors",
   adults: "Adults",
   kids: "Kids",
   license_plate: "License Plate",
   arrive_disribution: "If you will arrive at the distribution in a vehicle and know the license plate, please include it here. Sharing your license plate enables expedited check-in at some distributions.",
   house_hold_zip: "Household Zip code",
   registartion_register: "Register",
   for_foodbanks: "For Foodbanks",
   advance_registration: "Registering in advance is",
   by_registration: "By registering now, you can save time time on-site and keep yourself and our volunteers safe.",
   male: "Male",
   female: "Female",
   other: "Other",
   not_to_say: "Prefer Not To Specify",
   button_get_directions: "GET DIRECTIONS",
   button_view_details: "VIEW DETAILS",
   button_rsvp: "RSVP",
   button_reserve_time: "RESERVE TIME",
   button_register: "Register",
   button_login: "Login",
   button_logout: "Logout",
   button_profile: "Profile",
   button_settings: "Settings",
   button_help: "Help",
   button_back: "Back",
   button_next: "Next",
   button_submit: "Submit",
   button_cancel: "Cancel",
   button_save: "Save",
   button_delete: "Delete",
   button_edit: "Edit",
   date_from: "From",
   date_to: "To",
   date_range: "Date Range",
   date_range_placeholder: "Select Date Range",
   date_range_placeholder_from: "From",
   date_range_placeholder_to: "To",
   food_bank_serving: "Food Bank Serving Zip Code"

 },
 
 spa: {
  home_freshtrack:"FreshTrak está aquí para ayudar!",
  home_stay:"manténgase al tanto",
  home_findfood:"Encontrar comida",
  home_comming_soon:"Próximamente ... Cree una cuenta FreshTrak para mantenerse al tanto sobre los eventos locales de acceso a alimentos.",   
  home_zip_details:"Rellena con su código postal y conéctese a los recursos de acceso a alimentos en su comunidad.",  
  home_header_component:"¡Estamos aquí para ayudar! Rellena con su código postalpara encontrar recursos de acceso a alimentos en su comunidad.",   
  home_dashboard: "Proporciona más familias",   
  home_dashboard_org: "Prepara su organización para la abundancia de demanda de alimentos mediante la optimización del registro, la planificación de las ventanasde servicio y la previsión de necesidades. Sirva a más familias, tanto nuevas como actuales, en su comunidad.",   
  home_before_footer1: "Registre a los vecinos con anticipación o, cuando sea posible, programe una cita de recogida, su organización puede planificar cualquier aumento en la demanda.",   
  home_before_footer2: "Usted publica eventos de acceso a alimentos en su comunidad, desde el horario diario de la despensa hasta eventos emergentes de alimentos, y los vecinos rellenan sus códigos postals para conectarse con ellos.",   
  home_before_footer3: "Elimine el cuello de botella de la distribución con el registro previo del cliente en línea. ¡Atienda a más clientes de forma segura!",   
  home_before_footer1_header: "Pronostica la necesidad",   
  home_before_footer2_header: "Servir comida",   
  home_before_footer3_header:"Muévete rápido",   
  search_for_resources: "Buscar recursos",   
  resource_zip_code: "Eventos de recursos en código postal",   
  resource_zip_code_events:"Eventos de recursos que sirven a los residentes del código postal",   
  no_events_scheduled:"No hay eventos programados actualmente",   
  refine_your_results:"REFINA TUS RESULTADOS",   
  by_distance: "a distancia",   
  by_service_catogory: "por categoría de servicio",   
  register: "Regístrate ahora.",   
  save_time: "Ahorrar tiempo.",   
  stay_safe: "Privado y seguro.",   
  register_who_are_you:"Quien eres",   
  first_name: "Nombre",   
  middle_name: "segundo nombre",   
  last_name: "apellido",   
  suffix: "Sufijo",   
  dob:"Fecha de nacimiento",   
  gender: "Género",   
  register_where_you_live: "Donde vives",   
  street_address: "Dirección",   
  lot_suite: "apto/lote/suite",   
  city:"Ciudad",   
  state:"Estado",   
  zip_code:"Código postal",   
  register_how_to_contact: "Cómo contactarlo",   
  phone_number: "Número de teléfono (móvil preferido)",   
  no_phone: "No hay teléfono disponible",   
  phone_contact_you: "¿Está bien comunicarnos con usted con actualizaciones e información sobre su registro y actualizaciones de nuestra red?",   
  no_email: "No hay correo electrónico disponible",   
  email_contact_you:"¿Está bien enviarle un correo electrónico con actualizaciones e información sobre su registro y actualizaciones de nuestra red?",   
  register_about_family:"Háblanos de tu familia",   
  family_count: "¿Cuántos miembros adicionales de la familia hay en cada grupo de edad? (No te incluyas a ti mismo)",   
  seniors:"Personas mayores",   
  adults: "Adultas",   
  kids: "Niñas/Niños",   
  license_plate: "Matrícula",   
  arrive_disribution: "Si va a llegar a la distribución en un vehículo y sabe laplaca, inclúyala aquí. Compartir su matrícula permite hacer el check-in rápido enalgunas distribuciones.",
  house_hold_zip: "Código postal del hogar",
  registartion_register: "Registrarse",
  for_foodbanks: "Para bancos de alimentos",
  advance_registration: "Registrarse con anticipación es",
  by_registration: "Al registrarse ahora, puede ahorrar tiempo en el sitio y mantenerse a salvo a usted y a nuestros voluntarios.",
  male: "Masculina",
  female: "Mujer",
  other: "Otra/Otro",
  not_to_say: "Prefiero no especificar",
  button_get_directions: "OBTENER DIRECCIONES",
  button_view_details: "VER DETALLES",
  button_rsvp: "CONFIRMAR ASISTENCIA",
  button_reserve_time: "RESERVAR HORA",
  button_register: "Registrarse",
  button_login: "Iniciar sesión",
  button_logout: "Cerrar sesión",
  button_profile: "Perfil",
  button_settings: "Configuración",
  button_help: "Ayuda",
  button_back: "Atrás",
  button_next: "Siguiente",
  button_submit: "Enviar",
  button_cancel: "Cancelar",
  button_save: "Guardar",
  button_delete: "Eliminar",
  button_edit: "Editar",
  date_from: "Desde",
  date_to: "Hasta",
  date_range: "Rango de fechas",
  date_range_placeholder: "Seleccionar rango de fechas",
  date_range_placeholder_from: "Desde",
  date_range_placeholder_to: "Hasta",
  food_bank_serving: "Banco de alimentos que sirve al código postal"

 },
 som: {
  home_freshtrack:"FreshTrak waxay halkan u joogtaa inay ku caawiso!",
  home_stay:"La Soco Ilaa Taariikhda",
  home_findfood:"Cunno hel",
  home_comming_soon:"Goor dhow imaanaya ... Samee xisaab FreshTrak ah si aad ula socotid dhacdooyinka helitaanka cuntada ee maxalliga ah.",
  home_zip_details:"Gali nambarkaaga sifo aadna ugu xirnaato ilaha helitaanka cuntada ee bulshadaada.",
  home_header_component:"Waxaan halkaan u joognaa inaan ku caawinno! Gali nambarkaaga si aad uga hesho kheyraadka marin u helka cuntada bulshadaada.",
  home_dashboard: "U Adeer Qoys Dheeraad ah",
  home_dashboard_org: "U diyaari ururkaaga qulqulka baahida cuntada adoo hagaajinaya diiwaangelinta, daaqadaha adeegga qorsheynta, iyo baahida saadaalinta. U adeegso qoysas badan - kuwa hadda iyo kuwa cusubba — ee bulshadaada dhexdeeda.",
  home_before_footer1: "Diiwaangeli deriska ka hor waqtiga ama, halka ay suurtagal tahay, jadwal ballanta soo qaadista, ururkaagu wuxuu qorsheyn karaa koror kasta oo baahida ah.",
  home_before_footer2: "Waxaad soo dhigtaa marin u helka cuntada “dhacdooyinka” ee bulshadaada dhexdeeda-wax kasta oo ka yimaada saacadaha maalinlaha ah ilaa munaasabadaha cuntada ee soo baxa - deriskuna waxay gashadaan nambarkooda si ay ula xiriiraan iyaga.",
  home_before_footer3: "Ka saar culeyska ka jira qaybinta adoo diiwaangelinaya macaamiisha qadka tooska ah. U adeeg macaamiil badan, si badbaado leh!",
  home_before_footer1_header: "Saadaal Baahi",
  home_before_footer2_header: "Cunso Cunto",
  home_before_footer3_header:"Si Deg Deg Ah U Dhaqaaq",
  search_for_resources: "Raadi Kheyraad",
  resource_zip_code: "Dhacdooyinka Kheyraadka ee Lambarka Zip",
  resource_zip_code_events:"Dhacdooyinka Kheyraadka ee loogu adeegayo Dadka Deggan Zip Code",
  no_events_scheduled:"Dhacdooyin Majiraan Waqtigaan la qorsheeyay",
  refine_your_results:"NATIIJADA NATIIJADAADA",
  by_distance: "by Maskaxdii Dunid",
  by_service_catogory: "by Qaybta Adeegga",
  register: "Isdiiwaangeli Hada.",
  save_time: "Waqti Badbaadi.",
  stay_safe: "Ammaan ahaw",
  register_who_are_you:"Yaad tahay",
  first_name: "Magaca koowaad",
  middle_name: "magaca dhexe",
  last_name: "magaca dambe",
  suffix: "Suufiyada",
  dob:"Taariikhda Dhalashada",
  gender: "Jinsiga",
  register_where_you_live: "Halka aad ku nooshahay",
  street_address: "Cinwaanka Jidka",
  lot_suite: "apt/lot/suite",
  city:"Magaalada",
  state:"Gobol",
  zip_code:"Zip Code",
  register_how_to_contact: "Sida Loola Soo Xiriiriyo",
  phone_number: "Lambarka taleefanka (Mobile doorbiday)",
  no_phone: "Taleefan lamaheli karo",
  phone_contact_you: "Ma caadi baa inaan kula soo xiriiro cusbooneysiinta iyo macluumaadka ku saabsan diiwaangelintaada, iyo cusbooneysiinta shabakadeena?",
  no_email: "Email Laheli Mayo",
  email_contact_you:"Ma caadi baa inaan kugu soo dirno cusbooneysiin iyo macluumaad ku saabsan diiwaangelintaada, iyo cusbooneysiinta shabakadeena?",
  register_about_family:"Reerkaaga wax nooga sheeg",
  family_count: "Immisa xubnood oo qoys ah ayaa ku jira da 'kasta? (Ha ku darin naftaada)",
  seniors:"Waayeelka",
  adults: "Dadka waaweyn",
  kids: "Carruurta",
  license_plate: "Taarikada Liisanka",
  arrive_disribution: "Haddii aad ku imaan doontid qeybinta gawaarida oo aad taqaan taarikada, fadlan ku dar halkan. Wadaagista taarikada liisankaaga ayaa awood u siinaysa hubinta degdegga ah qaybinta qaarkood.",
  house_hold_zip: "Lambarka boostada guriga",
  registartion_register: "Diiwaangeli",
  for_foodbanks: "For Foodbanks",
  advance_registration: "Isdiiwaangalinta hore waa",
  by_registration: "Marka aad isdiiwaangaliso hada, waxaad waqti kuheli kartaa goobta isla markaana naftaada iyo tabaruceyaasheena badbaadin kartaa.",
  male: "Lab",
  female: "Dheddig",
  other: "Kale",
  not_to_say: "Doorbida Inaan Cadeyn",
  button_get_directions: "HEL HAGAA",
  button_view_details: "ARKO FAHFAHIN",
  button_rsvp: "XAQIIJIN",
  button_reserve_time: "RESERVE WAKTIGA",
  button_register: "Diiwaangeli",
  button_login: "Gal",
  button_logout: "Ka bix",
  button_profile: "Profile",
  button_settings: "Settings",
  button_help: "Caawimo",
  button_back: "Dib u noqo",
  button_next: "Xiga",
  button_submit: "Dir",
  button_cancel: "Jooji",
  button_save: "Kaydi",
  button_delete: "Tir",
  button_edit: "Wax ka beddel",
  date_from: "Ka bilow",
  date_to: "Ilaa",
  date_range: "Kala soocida taariikhda",
  date_range_placeholder: "Dooro kala soocida taariikhda",
  date_range_placeholder_from: "Ka bilow",
  date_range_placeholder_to: "Ilaa",
  food_bank_serving: "Bankiga cuntada ee loogu adeegayo lambarka boostada"

},
rus: {
  home_freshtrack:"FreshTrak здесь, чтобы помочь!",
  home_stay:"Будьте в курсе",
  home_findfood:"Найти еду",
  home_comming_soon:"Скоро ... Создайте учетную запись FreshTrak, чтобы быть в курсе местных событий по доступу к еде.",
  home_zip_details:"Введите свой почтовый индекс и подключитесь к ресурсам по доступу к еде в вашем районе.",
  home_header_component:"Мы здесь, чтобы помочь! Введите свой почтовый индекс, чтобы найти ресурсы по доступу к еде в вашем районе.",
  home_dashboard: "Подавать больше семьи",
  home_dashboard_org: "Подготовьте свою организацию к увеличению спроса на продукты питания путем оптимизации регистрации, планирования периодов обслуживания и прогнозирования потребностей. Обслуживайте больше семей - как нынешних, так и новых - в вашем районе.",
  home_before_footer1: "Зарегистрируйте соседей заранее или, если возможно, назначьте встречу с трансфером, ваша организация может спланировать любое увеличение спроса.",
  home_before_footer2: "Вы публикуете в своем сообществе «события» доступа к еде - от ежедневных часов работы кладовой до всплывающих окон еды - и соседи вводят свой почтовый индекс, чтобы подключиться к ним.",
  home_before_footer3: "Устраните узкое место в распространении с помощью предварительной онлайн-регистрации клиентов. Безопасно обслуживайте больше клиентов!",
  home_before_footer1_header: "Прогнозировать потребность",
  home_before_footer2_header: "Подавать еду",
  home_before_footer3_header:"Быстро двигаться",
  search_for_resources: "Поиск ресурсов",
  resource_zip_code: "События ресурсов в почтовом индексе",
  resource_zip_code_events:"События ресурсов, обслуживающие жителей почтового индекса",
  no_events_scheduled:"В настоящее время нет запланированных мероприятий",
  refine_your_results:"Уточните свои результаты",
  by_distance: "по расстоянию",
  by_service_catogory: "по категории услуг",
  register: "Зарегистрируйтесь сейчас.",
  save_time: "Экономьте время.",
  stay_safe: "Оставайтесь в безопасности.",
  register_who_are_you:"Кто ты",
  first_name: "Имя",
  middle_name: "второе имя",
  last_name: "фамилия",
  suffix: "Суффикс",
  dob:"Дата рождения",
  gender: "Пол",
  register_where_you_live: "Где вы живете",
  street_address: "Адрес улицы",
  lot_suite: "квартира/лот/люкс",
  city:"Город",
  state:"Состояние",
  zip_code:"Почтовый Индекс",
  register_how_to_contact: "Как с Вами связаться",
  phone_number: "Номер телефона (предпочтительно мобильный)",
  no_phone: "Телефон недоступен",
  phone_contact_you: "Можно ли связываться с вами с обновлениями и информацией о вашей регистрации и обновлениями в нашей сети?",
  no_email: "Электронная почта недоступна",
  email_contact_you:"Можно ли отправлять вам по электронной почте обновления и информацию о вашей регистрации и обновлениях в нашей сети?",
  register_about_family:"Расскажи нам о своей семье",
  family_count: "Сколько дополнительных членов семьи в каждой возрастной группе? (Не включайте себя)",
  seniors:"Пожилые люди",
  adults: "взрослые люди",
  kids: "Дети",
  license_plate: "Номерной знак",
  arrive_disribution: "Если вы приедете на раздачу на автомобиле и знаете номерной знак, укажите его здесь. Совместное использование номерного знака позволяет ускорить регистрацию на рейс в некоторых магазинах.",
  house_hold_zip: "Почтовый индекс домашнего хозяйства",
  registartion_register: "регистр",
  for_foodbanks: "Для Фудбанков",
  advance_registration: "Предварительная регистрация - это",
  by_registration: "Регистрируясь сейчас, вы можете сэкономить время на работе и обезопасить себя и наших волонтеров.",
  male: "Мужской",
  female: "женский",
  other: "Другой",
  not_to_say: "Предпочитаю не указывать",
  button_get_directions: "ПОЛУЧИТЬ НАПРАВЛЕНИЯ",
  button_view_details: "ПОСМОТРЕТЬ ДЕТАЛИ",
  button_rsvp: "ПОДТВЕРДИТЬ УЧАСТИЕ",
  button_reserve_time: "ЗАБРОНИРОВАТЬ ВРЕМЯ",
  button_register: "Зарегистрироваться",
  button_login: "Войти",
  button_logout: "Выйти",
  button_profile: "Профиль",
  button_settings: "Настройки",
  button_help: "Помощь",
  button_back: "Назад",
  button_next: "Далее",
  button_submit: "Отправить",
  button_cancel: "Отмена",
  button_save: "Сохранить",
  button_delete: "Удалить",
  button_edit: "Редактировать",
  date_from: "От",
  date_to: "До",
  date_range: "Диапазон дат",
  date_range_placeholder: "Выберите диапазон дат",
  date_range_placeholder_from: "От",
  date_range_placeholder_to: "До",
  food_bank_serving: "Продовольственный банк, обслуживающий почтовый индекс"

},
 tur: {
  home_freshtrack:"FreshTrak yardım etmek için burada!",
  home_stay:"Güncel kal",
  home_findfood:"Yiyecek bul",
  home_comming_soon:"Yakında ... Yerel yiyecek erişim etkinliklerinden haberdar olmak için bir FreshTrak hesabı oluşturun.",
  home_zip_details:"Posta kodunuzu girin ve topluluğunuzdaki yiyecek erişim kaynaklarına bağlanın.",
  home_header_component:"Yardım etmek için buradayız! Topluluğunuzdaki yiyecek erişim kaynaklarını bulmak için posta kodunuzu girin.",
  home_dashboard: "Daha Fazla Aile Servis Et",
  home_dashboard_org: "Kaydı düzene sokarak, hizmet pencerelerini planlayarak ve ihtiyaçları öngörerek kuruluşunuzu gıda talebi akışına hazırlayın. Topluluğunuzda hem mevcut hem de yeni olmak üzere daha fazla aileye hizmet edin.",
  home_before_footer1: "Komşularınızı önceden kaydedin veya mümkünse bir karşılama randevusu ayarlayın, kuruluşunuz talepte herhangi bir artış planlayabilir.",
  home_before_footer2: "Topluluğunuzda günlük kiler saatlerinden pop-up yemek etkinliklerine kadar yiyecek erişimi etkinlikleri yayınlarsınız ve komşular bunlarla bağlantı kurmak için posta kodlarını girer.",
  home_before_footer3: "Çevrimiçi müşteri ön kaydı ile darboğazı dağıtımdan kaldırın. Daha fazla müşteriye güvenle hizmet verin!",
  home_before_footer1_header: "İhtiyacı Tahmin Et",
  home_before_footer2_header: "Yemek servis etmek",
  home_before_footer3_header:"Hızlı hareket et",
  search_for_resources: "Kaynakları Ara",
  resource_zip_code: "Posta Kodundaki Kaynak Olayları",
  resource_zip_code_events:"Posta Kodu Sakinlerine Hizmet Veren Kaynak Olayları",
  no_events_scheduled:"Şu anda Planlanmış Etkinlik Yok",
  refine_your_results:"SONUÇLARINIZI DÜZELTİN",
  by_distance: "Mesafeye göre",
  by_service_catogory: "Hizmet Kategorisine göre",
  register: "Şimdi üye Ol.",
  save_time: "Zamandan tasarruf.",
  stay_safe: "Güvende kal.",
  register_who_are_you:"Sen kimsin",
  first_name: "İsim",
  middle_name: "ikinci ad",
  last_name: "Soyadı",
  suffix: "Sonek",
  dob:"Doğum tarihi",
  gender: "Cinsiyet",
  register_where_you_live: "Nerede yaşıyorsun",
  street_address: "Sokak adresi",
  lot_suite: "apt/lot/süit",
  city:"Kent",
  state:"Durum",
  zip_code:"Posta kodu",
  register_how_to_contact: "Nasıl iletişim kurabilirim",
  phone_number: "Telefon Numarası (Mobil Tercihli)",
  no_phone: "Telefon Yok",
  phone_contact_you: "Kaydınızla ilgili güncellemeler ve bilgiler ve ağımızdaki güncellemeler için sizinle iletişime geçebilir miyim?",
  no_email: "Kullanılabilir E-posta Yok",
  email_contact_you:"Kaydınızla ilgili güncellemeler ve bilgiler ve ağımızdaki güncellemeler ile size e-posta gönderebilir miyim?",
  register_about_family:"Bize ailenden bahset",
  family_count: "Her yaş grubunda kaç aile üyesi daha var? (Kendinizi dahil etmeyin)",
  seniors:"Yaşlılar",
  adults: "Yetişkinler",
  kids: "Çocuklar",
  license_plate: "Plaka",
  arrive_disribution: "Dağıtıma bir araçla gelecekseniz ve plakayı biliyorsanız, lütfen buraya ekleyin. Plakanızı paylaşmak, bazı dağıtımlarda hızlı check-in yapmanızı sağlar.",
  house_hold_zip: "Ev Posta kodu",
  registartion_register: "Kayıt ol",
  for_foodbanks: "Foodbanks için",
  advance_registration: "Önceden kayıt olmak",
  by_registration: "Şimdi kaydolarak, yerinde zaman kazanabilir ve kendinizi ve gönüllülerimizi güvende tutabilirsiniz.",
  male: "Erkek",
  female: "Kadın",
  other: "Diğer",
  not_to_say: "Belirtmemeyi Tercih Et",
  button_get_directions: "YÖN AL",
  button_view_details: "DETAYLARI GÖRÜNTÜLE",
  button_rsvp: "KATILIM ONAYLA",
  button_reserve_time: "ZAMAN AYIR",
  button_register: "Kayıt ol",
  button_login: "Giriş yap",
  button_logout: "Çıkış yap",
  button_profile: "Profil",
  button_settings: "Ayarlar",
  button_help: "Yardım",
  button_back: "Geri",
  button_next: "İleri",
  button_submit: "Gönder",
  button_cancel: "İptal",
  button_save: "Kaydet",
  button_delete: "Sil",
  button_edit: "Düzenle",
  date_from: "Başlangıç",
  date_to: "Bitiş",
  date_range: "Tarih aralığı",
  date_range_placeholder: "Tarih aralığı seçin",
  date_range_placeholder_from: "Başlangıç",
  date_range_placeholder_to: "Bitiş",
  food_bank_serving: "Posta koduna hizmet veren gıda bankası"


},
ara: {
  home_freshtrack:"FreshTrak هنا للمساعدة!",
  home_stay:"ابق على اطلاع",
  home_findfood:"ابحث عن الطعام",
  home_comming_soon:"قريبًا ... قم بإنشاء حساب FreshTrak للبقاء على اطلاع دائم بأحداث الوصول إلى الطعام المحلي.",
  home_zip_details:"أدخل الرمز البريدي الخاص بك واتصل بموارد الوصول إلى الطعام في مجتمعك.",
  home_header_component:"نحن هنا للمساعدة! أدخل الرمز البريدي الخاص بك للعثور على موارد الوصول إلى الطعام في مجتمعك.",
  home_dashboard: "خدمة المزيد من العائلة",
  home_dashboard_org: "جهز مؤسستك لتدفق الطلب على الغذاء من خلال تبسيط التسجيل وتخطيط نوافذ الخدمة والتنبؤ بالاحتياجات. خدمة المزيد من العائلات - الحالية والجديدة - في مجتمعك.",
  home_before_footer1: "قم بتسجيل الجيران في وقت مبكر أو ، حيثما أمكن ، حدد موعدًا للاستلام ، يمكن لمؤسستك التخطيط لأي زيادة في الطلب.",
  home_before_footer2: "تنشر أحداث الوصول إلى الطعام في مجتمعك — أي شيء بدءًا من ساعات تخزين الطعام اليومية إلى أحداث الطعام المنبثقة — ويقوم الجيران بإدخال الرمز البريدي الخاص بهم للتواصل معهم.",
  home_before_footer3: "قم بإزالة عنق الزجاجة من التوزيع مع التسجيل المسبق للعملاء عبر الإنترنت. خدمة المزيد من العملاء بأمان!",
  home_before_footer1_header: "توقع الحاجة",
  home_before_footer2_header: "تقديم الطعام",
  home_before_footer3_header:"تحرك بسرعة",
  search_for_resources: "ابحث عن الموارد",
  resource_zip_code: "أحداث المورد في الرمز البريدي",
  resource_zip_code_events:"أحداث المورد التي تخدم سكان الرمز البريدي",
  no_events_scheduled:"لا توجد أحداث مجدولة حاليا",
  refine_your_results:"حسّن نتائجك",
  by_distance: "عن طريق المسافة",
  by_service_catogory: "حسب فئة الخدمة",
  register: "سجل الان.",
  save_time: "وفر الوقت.",
  stay_safe: "ابق آمنًا.",
  register_who_are_you:"من أنت",
  first_name: "الاسم الاول",
  middle_name: "الاسم الأوسط",
  last_name: "الكنية",
  suffix: "لاحقة",
  dob:"تاريخ الولادة",
  gender: "جنس تذكير أو تأنيث",
  register_where_you_live: "اين تعيش",
  street_address: "عنوان الشارع",
  lot_suite: "مناسبة / الكثير / جناح",
  city:"مدينة",
  state:"حالة",
  zip_code:"الرمز البريدي",
  register_how_to_contact: "كيفية الاتصال بك",
  phone_number: "رقم الهاتف (يفضل الجوال)",
  no_phone: "لا يوجد هاتف متاح",
  phone_contact_you: "هل من المقبول الاتصال بك للحصول على تحديثات ومعلومات حول تسجيلك وتحديثات لشبكتنا؟",
  no_email: "لا يوجد بريد إلكتروني متاح",
  email_contact_you:"هل من المقبول مراسلتك عبر البريد الإلكتروني بالتحديثات والمعلومات حول التسجيل والتحديثات الخاصة بشبكتنا؟",
  register_about_family:"أخبرنا عن عائلتك",
  family_count: "كم عدد أفراد الأسرة الإضافيين في كل فئة عمرية؟ (لا تشمل نفسك)",
  seniors:"كبار السن",
  adults: "الكبار",
  kids: "أطفال",
  license_plate: "لوحة الترخيص",
  arrive_disribution: "إذا كنت ستصل إلى التوزيع في سيارة وتعرف لوحة الترخيص ، فيرجى تضمينها هنا. تتيح مشاركة لوحة الترخيص الخاصة بك تسجيل الوصول السريع في بعض التوزيعات.",
  house_hold_zip: "الرمز البريدي للمنزل",
  registartion_register: "يسجل",
  for_foodbanks: "لبنوك الطعام",
  advance_registration: "التسجيل مقدما هو",
  by_registration: "من خلال التسجيل الآن ، يمكنك توفير الوقت في الموقع والحفاظ على سلامتك أنت ومتطوعينا.",
  male: "ذكر",
  female: "أنثى",
  other: "آخر",
  not_to_say: "تفضل عدم التحديد",
  button_get_directions: "احصل على الاتجاهات",
  button_view_details: "عرض التفاصيل",
  button_rsvp: "تأكيد الحضور",
  button_reserve_time: "حجز الوقت",
  button_register: "تسجيل",
  button_login: "تسجيل الدخول",
  button_logout: "تسجيل الخروج",
  button_profile: "الملف الشخصي",
  button_settings: "الإعدادات",
  button_help: "مساعدة",
  button_back: "رجوع",
  button_next: "التالي",
  button_submit: "إرسال",
  button_cancel: "إلغاء",
  button_save: "حفظ",
  button_delete: "حذف",
  button_edit: "تعديل",
  date_from: "من",
  date_to: "إلى",
  date_range: "نطاق التاريخ",
  date_range_placeholder: "اختر نطاق التاريخ",
  date_range_placeholder_from: "من",
  date_range_placeholder_to: "إلى",
  food_bank_serving: "بنك الطعام الذي يخدم الرمز البريدي"

},
zho: {
  home_freshtrack:"FreshTrak在這里為您提供幫助",
  home_stay:"保持最新",
  home_findfood:"找食物",
  home_comming_soon:"即將推出...註冊一個FreshTrak帳戶，以隨時了解當地的食物獲取活動。",
  home_zip_details:"輸入您的郵政編碼，並連接到您社區中的食物獲取資源。",
  home_header_component:"我们在这里为您提供帮助！输入您的邮政编码以查找社区中的食物获取资源。",
  home_dashboard: "服务更多家庭",
  home_dashboard_org: "通过简化注册，计划服务窗口和预测需求，为组织准备好迎接食品需求的增长。在您的社区中为更多家庭提供服务（无论是现有的还是新的）。",
  home_before_footer1: "提前注册邻居，或者在可能的情况下安排接送约会，您的组织可以计划任何需求的增长。",
  home_before_footer2: "您可以在社区中发布食物获取事件（从每天的茶水时间到弹出式食物事件），并且邻居输入邮政编码以与他们建立联系。",
  home_before_footer3: "通过在线客户预先注册，消除了分销的瓶颈。安全地服务更多的客户！",
  home_before_footer1_header: "预测需求",
  home_before_footer2_header: "提供食物",
  home_before_footer3_header: "动作快点",
  search_for_resources: "搜索资源",
  resource_zip_code: "邮政编码中的资源事件",
  resource_zip_code_events:"为居民提供服务的资源事件",
  no_events_scheduled:"目前未安排活动",
  refine_your_results:"完善您的结果",
  by_distance: "按距离",
  by_service_catogory: "按服务类别",
  register: "现在注册。",
  save_time: "省时间。",
  stay_safe: "注意安全。",
  register_who_are_you:"你是谁",
  first_name: "名",
  middle_name: "中间名字",
  last_name: "姓",
  suffix: "后缀",
  dob:"出生日期",
  gender: "性别",
  register_where_you_live: "你住的地方",
  street_address: "街道地址",
  lot_suite: "apt/lot/suite",
  city:"城市",
  state:"状态",
  zip_code:"邮政编码",
  register_how_to_contact: "如何与您联系",
  phone_number: "电话号码（首选移动电话）",
  no_phone: "没有可用的电话",
  phone_contact_you: "是否可以与您联系以获取有关注册的更新和信息以及我们网络的更新",
  no_email: "没有可用的电子邮件",
  email_contact_you:"可以通过电子邮件向您发送有关注册的更新和信息以及我们网络的更新吗",
  register_about_family:"告诉我们你的家人",
  family_count: "每个年龄段还有多少家庭成员？ （不要包括自己)",
  seniors:"老年人",
  adults: "成年人",
  kids: "孩子们",
  license_plate: "牌照",
  arrive_disribution: "如果您将乘坐汽车到达配送区，并且知道车牌，请在此处提供。共享您的车牌可以在某些发行版中加快签到。",
  house_hold_zip: "家用邮政编码",
  registartion_register: "登记",
  for_foodbanks: "对于食品银行",
  advance_registration: "提前注册为",
  by_registration: "通过立即注册，您可以节省现场时间，并确保自己和我们的志愿者的安全。",
  male: "男性",
  female: "女性",
  other: "其他",
  not_to_say: "不想指定",
  button_get_directions: "获取路线",
  button_view_details: "查看详情",
  button_rsvp: "确认参加",
  button_reserve_time: "预约时间",
  button_register: "注册",
  button_login: "登录",
  button_logout: "登出",
  button_profile: "个人资料",
  button_settings: "设置",
  button_help: "帮助",
  button_back: "返回",
  button_next: "下一步",
  button_submit: "提交",
  button_cancel: "取消",
  button_save: "保存",
  button_delete: "删除",
  button_edit: "编辑",
  date_from: "从",
  date_to: "到",
  date_range: "日期范围",
  date_range_placeholder: "选择日期范围",
  date_range_placeholder_from: "从",
  date_range_placeholder_to: "到",
  food_bank_serving: "为该邮政编码服务的食品银行"

},
hin: {
  home_freshtrack:"FreshTrak मदद करने के लिए यहाँ है!",
  home_stay:"अद्यतन रहना",
  home_findfood:"भोजन तलाशें",
  home_comming_soon:"जल्द ही आ रहा है ... स्थानीय भोजन के उपयोग की घटनाओं पर तारीख तक रहने के लिए एक FreshTrak खाता बनाएँ।",
  home_zip_details:"अपना ज़िप कोड दर्ज करें और अपने समुदाय में भोजन पहुंच संसाधनों से जुड़े।",
  home_header_component:"हमलोग यहां सहायता करने के लिए हैं! अपने समुदाय में खाद्य पहुंच संसाधनों को खोजने के लिए अपना ज़िप कोड इनपुट करें।",
  home_dashboard: "अधिक परिवार की सेवा करें",
  home_dashboard_org: "पंजीकरण, योजना खिड़की, और पूर्वानुमान आवश्यकताओं को सुव्यवस्थित करके भोजन की मांग की आमद के लिए अपने संगठन को तैयार करें। और अधिक परिवारों की सेवा करें - आपके समुदाय में वर्तमान और नए दोनों।",
  home_before_footer1: "समय से पहले पड़ोसियों को पंजीकृत करें या जहां संभव हो, पिक अप अपॉइंटमेंट शेड्यूल करें, आपका संगठन मांग में किसी भी वृद्धि के लिए योजना बना सकता है।",
  home_before_footer2: "आप अपने समुदाय में भोजन पहुंच की घटनाओं को पोस्ट करते हैं - दैनिक पैंट्री घंटे से लेकर पॉप-अप फूड इवेंट तक कुछ भी - और पड़ोसी उनसे जुड़ने के लिए अपना ज़िप कोड दर्ज करते हैं।",
  home_before_footer3: "ऑनलाइन ग्राहक पूर्व पंजीकरण के साथ वितरण से अड़चन को दूर करें। अधिक ग्राहकों की सेवा करें, सुरक्षित रूप से!",
  home_before_footer1_header: "भविष्यवाणी की जरूरत है",
  home_before_footer2_header: "भोजन परोसे",
  home_before_footer3_header:"जल्दी चलो",
  search_for_resources: "संसाधनों के लिए खोज",
  resource_zip_code: "ज़िप कोड में संसाधन घटनाएँ",
  resource_zip_code_events:"ज़िप कोड के निवासियों की सेवा के संसाधन कार्यक्रम",
  no_events_scheduled:"वर्तमान में कोई कार्यक्रम निर्धारित नहीं है",
  refine_your_results:"अपने परिणामों को पढ़ें",
  by_distance: "दूरी द्वारा",
  by_service_catogory: "सेवा श्रेणी द्वारा",
  register: "अभी पंजीकरण करें।",
  save_time: "समय बचाओ।",
  stay_safe: "सुरक्षित रहें।",
  register_who_are_you:"आप कौन हैं",
  first_name: "नाम",
  middle_name: "मध्य नाम",
  last_name: "उपनाम",
  suffix: "प्रत्यय",
  dob:"जन्म की तारीख",
  gender: "लिंग",
  register_where_you_live: "तुम कहा रहते हो",
  street_address: "गली का पता",
  lot_suite: "उपयुक्त/बहुत/सूट",
  city:"फरीदाबाद",
  state:"राज्य",
  zip_code:"ज़िप कोड",
  register_how_to_contact: "आपसे कैसे संपर्क करें",
  phone_number: "फ़ोन नंबर (मोबाइल पसंदीदा)",
  no_phone: "कोई फोन उपलब्ध नहीं है",
  phone_contact_you: "क्या आपको अपने पंजीकरण के बारे में जानकारी और जानकारी और हमारे नेटवर्क के अपडेट से संपर्क करना ठीक है?",
  no_email: "कोई ईमेल उपलब्ध नहीं है",
  email_contact_you:"क्या आपको अपने पंजीकरण के बारे में जानकारी और जानकारी और हमारे नेटवर्क के अपडेट के साथ ईमेल करना ठीक है?",
  register_about_family:"अपने परिवार के बारे में हमें बताएं",
  family_count: "प्रत्येक आयु वर्ग में कितने अतिरिक्त परिवार के सदस्य हैं? (खुद को शामिल न करें)",
  seniors:"वरिष्ठ",
  adults: "वयस्कों",
  kids: "बच्चे",
  license_plate: "लाइसेंस प्लेट",
  arrive_disribution: "यदि आप एक वाहन में वितरण पर पहुंचेंगे और लाइसेंस प्लेट को जानेंगे, तो कृपया इसे यहां शामिल करें। अपनी लाइसेंस प्लेट साझा करना कुछ वितरणों में शीघ्र चेक-इन सक्षम बनाता है।",
  house_hold_zip: "घरेलू ज़िप कोड",
  registartion_register: "रजिस्टर करें",
  for_foodbanks: "फूडबैंक के लिए",
  advance_registration: "अग्रिम में पंजीकरण है",
  by_registration: "अब पंजीकरण करके, आप साइट पर समय बचा सकते हैं और अपने आप को और हमारे स्वयंसेवकों को सुरक्षित रख सकते हैं।",
  male: "पुरुष",
  female: "महिला",
  other: "अन्य",
  not_to_say: "निर्दिष्ट नहीं करना चाहते हैं",
  button_get_directions: "दिशा प्राप्त करें",
  button_view_details: "विवरण देखें",
  button_rsvp: "उपस्थिति की पुष्टि करें",
  button_reserve_time: "समय आरक्षित करें",
  button_register: "पंजीकरण करें",
  button_login: "लॉगिन करें",
  button_logout: "लॉगआउट करें",
  button_profile: "प्रोफ़ाइल",
  button_settings: "सेटिंग्स",
  button_help: "सहायता",
  button_back: "वापस",
  button_next: "अगला",
  button_submit: "सबमिट करें",
  button_cancel: "रद्द करें",
  button_save: "सहेजें",
  button_delete: "हटाएं",
  button_edit: "संपादित करें",
  date_from: "से",
  date_to: "तक",
  date_range: "तिथि सीमा",
  date_range_placeholder: "तिथि सीमा चुनें",
  date_range_placeholder_from: "से",
  date_range_placeholder_to: "तक",
  food_bank_serving: "पिन कोड की सेवा करने वाला खाद्य बैंक"

},
nep: {
  home_freshtrack:"फ्रेशट्र्याक मद्दत गर्न यहाँ छ!",
  home_stay:"अद्यावधिक रहनुहोस्",
  home_findfood:"खाना खोज्नुहोस्",
  home_comming_soon:"चाँडै आउँदैछ ... स्थानीय खाना पहुँच घटनाहरूमा अद्यावधिक रहन एक नयाँ ताजा खाता बनाउनुहोस्।",
  home_zip_details:"तपाईंको जिप कोड प्रविष्ट गर्नुहोस् र तपाईंको समुदायमा खाना पहुँच स्रोतहरूमा जडान हुनुहोस्।",
  home_header_component:"हामी यहाँ मद्दत गर्न आएका छौं! तपाईंको जिप कोड इनपुट गर्नुहोस् तपाईंको समुदायमा खाना पहुँच स्रोतहरू फेला पार्न।",
  home_dashboard: "अधिक Familie सेवा गर्नुहोस्",
  home_dashboard_org: "पंजीकरण, योजना बनाउने सेवा विन्डोजहरू, र पूर्वानुमान आवश्यकताहरूलाई सुव्यवस्थित गरेर खानाको मागको आवकको लागि तपाईंको संगठन तैयार गर्नुहोस्। तपाईंको समुदायमा थप परिवारहरू - दुबै वर्तमान र नयाँ Ser सेवा गर्दछन्।",
  home_before_footer1: "समय भन्दा पहिले छिमेकीहरू रेजिस्टर गर्नुहोस् वा जहाँ सम्भव छ, एक पिक-अप अपोइन्टमेन्ट अनुसूची गर्नुहोस्, तपाईंको संगठनले कुनै पनि मागको वृद्धिको लागि योजना गर्न सक्दछ।.",
  home_before_footer2: "तपाईं आफ्नो समुदायमा खाना पहुँच “घटनाहरू” पोष्ट गर्नुहुन्छ - पप-अप खाना घटनाहरूमा दैनिक पेन्ट्री घण्टा देखि केहि पनि — र छिमेकीहरूले तिनीहरूसँग जडान हुनको लागि उनीहरूको जिप कोड प्रविष्ट गर्छन्।",
  home_before_footer3: "अनलाइन ग्राहक पूर्व-दर्ता संग वितरण बाट अवरोध हटाउनुहोस्। अधिक ग्राहकहरूको सेवा गर्नुहोस्, सुरक्षित रूपमा!",
  home_before_footer1_header: "भविष्यवाणी आवश्यकता",
  home_before_footer2_header: "खाना परोस",
  home_before_footer3_header:"द्रुत रूपमा सार्नुहोस्",
  search_for_resources: "संसाधनहरूको लागि खोजी गर्नुहोस्",
  resource_zip_code: "जिप कोडमा स्रोत घटनाहरू",
  resource_zip_code_events:"Zip Code को बासिन्दाको सेवा गर्ने स्रोत घटनाक्रम",
  no_events_scheduled:"हाल कुनै कार्यक्रमहरू तालिकाबद्ध गरिएको छैन",
  refine_your_results:"तपाइँका परिणामहरूलाई परिष्कृत गर्नुहोस",
  by_distance: "दूरी बाट",
  by_service_catogory: "सेवा कोटी द्वारा",
  register: "अहिले नै दर्ता गर्नुहोस।",
  save_time: "समयकाे बचत गर।",
  stay_safe: "सुरक्षित रहनुहोस्।",
  register_who_are_you:"तिमी को हाै",
  first_name: "पहिलो नाम",
  middle_name: "बीचको नाम",
  last_name: "थर",
  suffix: "प्रत्यय",
  dob:"जन्म मिति",
  gender: "लि .्ग",
  register_where_you_live: "तपाई कहाँ बस्नु हुन्छ",
  street_address: "सडक ठेगाना",
  lot_suite: "apt/lot/suite",
  city:"शहर",
  state:"राज्य",
  zip_code:"जिप कोड",
  register_how_to_contact: "कसरी तपाईंलाई सम्पर्क गर्ने",
  phone_number: "फोन नम्बर (मोबाइल मनपर्दो)",
  no_phone: "कुनै फोन उपलब्ध छैन",
  phone_contact_you: "के तपाइँसँग तपाइँको रेजिष्ट्रेसनको बारेमा अद्यावधिक र जानकारी, र हाम्रो नेटवर्कमा अद्यावधिक जानकारीका साथ सम्पर्क गर्न ठीक छ?",
  no_email: "कुनै ईमेल उपलब्ध छैन",
  email_contact_you:"के तपाइँलाई तपाइँको पंजीकरणको बारेमा अद्यावधिक र जानकारी, र हाम्रो नेटवर्कमा अद्यावधिकको साथ ईमेल गर्न ठीक छ?",
  register_about_family:"तपाईंको परिवारको बारेमा हामीलाई भन्नुहोस्",
  family_count: "प्रत्येक उमेर समूहमा कति अतिरिक्त परिवार सदस्यहरू छन्? (आफूलाई समावेश नगर्नुहोस्)",
  seniors:"वरिष्ठहरु",
  adults: "वयस्कहरू",
  kids: "बच्चाहरू",
  license_plate: "नम्बर प्लेट",
  arrive_disribution: "यदि तपाईं गाडीमा वितरणमा आइपुग्नुहुनेछ र इजाजतपत्र प्लेट थाहा पाउनुहुनेछ भने, कृपया यहाँ समावेश गर्नुहोस्। तपाइँको इजाजत पत्र प्लेट साझा केहि वितरण मा छिटो चेक-इन सक्षम गर्दछ।",
  house_hold_zip: "घरेलु जिप कोड",
  registartion_register: "रेजिष्टर गर्नुहोस्",
  for_foodbanks: "Foodbanks को लागी",
  advance_registration: "अग्रिम दर्ता गर्नु हो",
  by_registration: "अहिले दर्ता गरेर, तपाईं साइटमा समय बचत गर्न सक्नुहुनेछ र आफैलाई र हाम्रा स्वयंसेवकहरूलाई सुरक्षित राख्न सक्नुहुन्छ।",
  male: "नर",
  female: "महिला",
  other: "अन्य",
  not_to_say: "निर्दिष्ट नगर्न मन पर्छ",
  button_get_directions: "दिशा प्राप्त गर्नुहोस्",
  button_view_details: "विवरण हेर्नुहोस्",
  button_rsvp: "उपस्थिति पुष्टि गर्नुहोस्",
  button_reserve_time: "समय आरक्षित गर्नुहोस्",
  button_register: "दर्ता गर्नुहोस्",
  button_login: "लगइन गर्नुहोस्",
  button_logout: "लगआउट गर्नुहोस्",
  button_profile: "प्रोफाइल",
  button_settings: "सेटिङहरू",
  button_help: "सहायता",
  button_back: "फिर्ता",
  button_next: "अर्को",
  button_submit: "पेश गर्नुहोस्",
  button_cancel: "रद्द गर्नुहोस्",
  button_save: "सुरक्षित गर्नुहोस्",
  button_delete: "मेटाउनुहोस्",
  button_edit: "सम्पादन गर्नुहोस्",
  date_from: "बाट",
  date_to: "सम्म",
  date_range: "मिति सीमा",
  date_range_placeholder: "मिति सीमा छान्नुहोस्",
  date_range_placeholder_from: "बाट",
  date_range_placeholder_to: "सम्म",
  food_bank_serving: "पिन कोडको सेवा गर्ने खाद्य बैंक"

},
tag: {
  home_freshtrack:"Nandito ang FreshTrak para tumulong!",
  home_stay:"Manatiling Na-update",
  home_findfood:"Maghanap ng Pagkain",
  home_comming_soon:"Malapit na... Gumawa ng FreshTrak account para manatiling na-update sa mga lokal na kaganapan sa pag-access ng pagkain.",
  home_zip_details:"Ipasok ang iyong zip code at kumonekta sa mga mapagkukunan ng pag-access sa pagkain sa iyong komunidad.",
  home_header_component:"Nandito kami para tumulong! Ipasok ang iyong zip code para mahanap ang mga mapagkukunan ng pag-access sa pagkain sa iyong komunidad.",
  home_dashboard: "Maglingkod sa Mas Maraming Pamilya",
  home_dashboard_org: "Ihanda ang iyong organisasyon para sa pagdagsa ng pangangailangan sa pagkain sa pamamagitan ng pag-streamline ng pagpaparehistro, pagpaplano ng mga window ng serbisyo, at pagtataya ng mga pangangailangan. Maglingkod sa mas maraming pamilya—parehong kasalukuyan at bago—sa iyong komunidad.",
  home_before_footer1: "Magparehistro ng mga kapitbahay nang maaga o, kung posible, mag-iskedyul ng appointment sa pag-pick up, ang iyong organisasyon ay maaaring magplano para sa anumang pagtaas sa pangangailangan.",
  home_before_footer2: "Nagpo-post ka ng mga kaganapan sa pag-access sa pagkain sa iyong komunidad—mula sa pang-araw-araw na oras ng pantry hanggang sa pop-up na mga kaganapan sa pagkain—at ang mga kapitbahay ay naglalagay ng kanilang zip code para makakonekta sa kanila.",
  home_before_footer3: "Alisin ang bottleneck mula sa pamamahagi sa online na pre-registration ng customer. Maglingkod sa mas maraming customer, nang ligtas!",
  home_before_footer1_header: "Hulaan ang Pangangailangan",
  home_before_footer2_header: "Maglingkod ng Pagkain",
  home_before_footer3_header:"Mabilis na Gumalaw",
  search_for_resources: "Maghanap ng Mga Mapagkukunan",
  resource_zip_code: "Mga Kaganapan ng Mapagkukunan sa Zip Code",
  resource_zip_code_events:"Mga Kaganapan ng Mapagkukunan na Naglilingkod sa mga Resident ng Zip Code",
  no_events_scheduled:"Walang mga Kaganapan na Naka-iskedyul Sa Ngayon",
  refine_your_results:"PINUHIN ANG IYONG MGA RESULTA",
  by_distance: "ayon sa Distansya",
  by_service_catogory: "ayon sa Kategorya ng Serbisyo",
  register: "Magparehistro Ngayon.",
  save_time: "Magtipid ng Oras.",
  stay_safe: "Manatiling Ligtas.",
  register_who_are_you:"Sino ka",
  first_name: "Pangalan",
  middle_name: "Gitnang Pangalan",
  last_name: "Apelyido",
  suffix: "Suffix",
  dob:"Petsa ng Kapanganakan",
  gender: "Kasarian",
  register_where_you_live: "Saan ka nakatira",
  street_address: "Address ng Kalye",
  lot_suite: "apt/lot/suite",
  city:"Lungsod",
  state:"Estado",
  zip_code:"Zip Code",
  register_how_to_contact: "Paano Makipag-ugnayan sa Iyo",
  phone_number: "Numero ng Telepono (Mas Gusto ang Mobile)",
  no_phone: "Walang Telepono na Magagamit",
  phone_contact_you: "Ayos lang ba na makipag-ugnayan sa iyo para sa mga update at impormasyon tungkol sa iyong pagpaparehistro, at mga update sa aming network?",
  no_email: "Walang Email na Magagamit",
  email_contact_you:"Ayos lang ba na mag-email sa iyo ng mga update at impormasyon tungkol sa iyong pagpaparehistro, at mga update sa aming network?",
  register_about_family:"Sabihin sa amin ang tungkol sa iyong pamilya",
  family_count: "Ilang karagdagang miyembro ng pamilya ang nasa bawat pangkat ng edad? (Huwag isama ang sarili mo)",
  seniors:"Mga Senior",
  adults: "Mga Adulto",
  kids: "Mga Bata",
  license_plate: "Plaka ng Lisensya",
  arrive_disribution: "Kung darating ka sa pamamahagi sa isang sasakyan at alam mo ang plaka, mangyaring isama ito dito. Ang pagbabahagi ng iyong plaka ay nagbibigay-daan sa mabilis na check-in sa ilang pamamahagi.",
  house_hold_zip: "Zip Code ng Sambahayan",
  registartion_register: "Magparehistro",
  for_foodbanks: "Para sa mga Foodbank",
  advance_registration: "Ang pagpaparehistro nang maaga ay",
  by_registration: "Sa pamamagitan ng pagpaparehistro ngayon, maaari kang makatipid ng oras sa site at mapanatili ang kaligtasan mo at ng aming mga volunteer.",
  male: "Lalaki",
  female: "Babae",
  other: "Iba",
  not_to_say: "Mas Gustong Hindi I-specify",
  button_get_directions: "KUNIN ANG MGA DIREKSYON",
  button_view_details: "TINGNAN ANG MGA DETALYE",
  button_rsvp: "KUMPIRMA ANG PAGDALO",
  button_reserve_time: "I-RESERVE ANG ORAS",
  button_register: "Magparehistro",
  button_login: "Mag-login",
  button_logout: "Mag-logout",
  button_profile: "Profile",
  button_settings: "Mga Setting",
  button_help: "Tulong",
  button_back: "Bumalik",
  button_next: "Susunod",
  button_submit: "Ipadala",
  button_cancel: "Kanselahin",
  button_save: "I-save",
  button_delete: "Tanggalin",
  button_edit: "I-edit",
  date_from: "Mula",
  date_to: "Hanggang",
  date_range: "Saklaw ng Petsa",
  date_range_placeholder: "Pumili ng Saklaw ng Petsa",
  date_range_placeholder_from: "Mula",
  date_range_placeholder_to: "Hanggang",
  food_bank_serving: "Food Bank na Naglilingkod sa Zip Code"

}
});

export default localization;